# Generated by Django 5.1.7 on 2025-05-17 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_booking_check_in_time_booking_check_out_time'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='booking',
        #     name='agreed_to_terms',
        # ),
        migrations.AddField(
            model_name='booking',
            name='agreement_pdf',
            field=models.FileField(blank=True, null=True, upload_to='agreements/'),
        ),
    ]
