# Generated by Django 5.1.7 on 2025-05-17 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_remove_booking_agreed_to_terms_booking_agreement_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='acknowledged',
            field=models.BooleanField(default=False),
        ),
    ]
