# Generated by Django 5.1.7 on 2025-05-21 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_booking_acknowledged'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=8),
        ),
    ]
