# Generated by Django 5.1.7 on 2025-05-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_booking_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='deposit_added',
            field=models.BooleanField(default=False),
        ),
    ]
