# Generated by Django 5.1.7 on 2025-05-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_booking_deposit_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='agreement_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
