# Generated by Django 5.1.7 on 2025-05-24 21:10

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_booking_agreement_uploaded'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarPicturesForTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_image', models.FileField(blank=True, null=True, upload_to='trip_images/')),
                ('hgid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvxyz', length=10, max_length=20, prefix='', unique=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.booking')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car')),
            ],
            options={
                'verbose_name_plural': 'Car Trip Photos',
            },
        ),
    ]
