# Generated by Django 5.1.7 on 2025-05-24 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_carpicturesfortrip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredcar',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car.car'),
        ),
    ]
