# Generated by Django 5.1.7 on 2025-05-24 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0010_alter_featuredcar_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carpicturesfortrip',
            name='car',
        ),
    ]
