# Generated by Django 5.1.7 on 2025-05-25 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0011_remove_carpicturesfortrip_car'),
    ]

    operations = [
    ]
