# Generated by Django 5.1.7 on 2025-05-25 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0012_auto_20250525_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='agreed_to_terms',
        ),
    ]
