
services:
  redis:
    image: redis:7
    container_name: rental_car_redis
    ports:
    - "6380:6379"
    networks: 
    - rental_car_app_django_network
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
           python manage.py runserver 0.0.0.0:8000"
    container_name: rental_car_app_web
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    ports:
      - "9345:8000"
    networks:
      - rental_car_app_django_network
    env_file:
      - .env 
    environment:
      - DATABASE_HOST=db

  
  celery:
    build: .
    container_name: rental_car_celery
    command: celery -A rental_car worker --loglevel=info
    volumes:
    - .:/app
    depends_on:
    - redis
    - web
    networks:
    - rental_car_app_django_network
    env_file:
    - .env

  celery_beat:
    build: .
    container_name: rental_car_celery_beat
    command: celery -A rental_car beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    depends_on:
      - redis
    networks:
      - rental_car_app_django_network
    env_file:
      - .env
  
volumes:
  static_volume:
    driver: local
  media_volume:
    driver: local
  db_data:
    driver: local

networks:
  rental_car_app_django_network:
    driver: bridge
