version: '3.8'

services:
  redis:
    image: redis:7
    container_name: rental_car_redis_prod
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks: 
      - rental_car_app_django_network
    volumes:
      - redis_data:/data

  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn rental_car.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 120"
    container_name: rental_car_app_web_prod
    restart: unless-stopped
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    ports:
      - "8000:8000"
    networks:
      - rental_car_app_django_network
    env_file:
      - .env.prod
    depends_on:
      - redis

  celery:
    build: .
    container_name: rental_car_celery_prod
    restart: unless-stopped
    command: celery -A rental_car worker --loglevel=info --concurrency=2
    volumes:
      - media_volume:/app/mediafiles
    depends_on:
      - redis
      - web
    networks:
      - rental_car_app_django_network
    env_file:
      - .env.prod

  celery_beat:
    build: .
    container_name: rental_car_celery_beat_prod
    restart: unless-stopped
    command: celery -A rental_car beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - media_volume:/app/mediafiles
    depends_on:
      - redis
      - web
    networks:
      - rental_car_app_django_network
    env_file:
      - .env.prod

volumes:
  static_volume:
  media_volume:
  redis_data:

networks:
  rental_car_app_django_network:
    driver: bridge