# Generated by Django 5.1.7 on 2025-05-09 16:54

import django.core.validators
import user_auths.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='drivers_license',
            field=models.FileField(blank=True, null=True, upload_to=user_auths.models.license_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])]),
        ),
    ]
