# Generated by Django 5.1.7 on 2025-05-11 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auths', '0003_alter_profile_drivers_license_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
