# Generated by Django 5.1.7 on 2025-05-14 23:31

import django.core.files.storage
import django.core.validators
import user_auths.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auths', '0004_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='drivers_license',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/app/secure_files'), upload_to=user_auths.models.license_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, storage=django.core.files.storage.FileSystemStorage(location='/app/secure_files'), upload_to=user_auths.models.user_directory_path),
        ),
    ]
